/**
 * @helium/ts-tsoa-api
 * Helium API with TSOA generator and openAPI sdk generator
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* From T, pick a set of properties whose keys are in the union K
*/
export class PickServiceExcludeKeyofServiceId {
    /**
    * The name of the Service
    */
    'name': string;
    /**
    * Description of the service
    */
    'description': string;
    'steps': Array<string>;
    /**
    * Systems the Service is affecting
    */
    'systems': Array<string>;
    /**
    * parts being affected by the service
    */
    'partsServiced': Array<string>;
    'newParts': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<string>"
        },
        {
            "name": "systems",
            "baseName": "systems",
            "type": "Array<string>"
        },
        {
            "name": "partsServiced",
            "baseName": "partsServiced",
            "type": "Array<string>"
        },
        {
            "name": "newParts",
            "baseName": "newParts",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return PickServiceExcludeKeyofServiceId.attributeTypeMap;
    }
}

