/**
 * @helium/ts-tsoa-api
 * Helium API with TSOA generator and openAPI sdk generator
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* From T, pick a set of properties whose keys are in the union K
*/
export class PickSystemExcludeKeyofSystemId {
    /**
    * The name of the system
    */
    'name': string;
    /**
    * A full description of the system
    */
    'description': string;
    /**
    * Short summary of the system
    */
    'summary': string;
    'referencedParts': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "referencedParts",
            "baseName": "referencedParts",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return PickSystemExcludeKeyofSystemId.attributeTypeMap;
    }
}

