/**
 * @helium/ts-tsoa-api
 * Helium API with TSOA generator and openAPI sdk generator
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* From T, pick a set of properties whose keys are in the union K
*/
export class PickPartExcludeKeyofPartId {
    /**
    * The name of the part
    */
    'name': string;
    /**
    * Systems the part can be used in
    */
    'system': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "system",
            "baseName": "system",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return PickPartExcludeKeyofPartId.attributeTypeMap;
    }
}

